---
version: '3'

services:
  backend:
    container_name: backend
    build: ./backend 

# TODO configure wordpress
  frontend:
    container_name: frontend
    build: ./frontend 
    #Configure the environment variables to connect to the database.
    environment:
      - BACKEND_DNS=backend
    depends_on: 
      - backend
    ports:
      - "8080:8080"


    # TODO configure mysql
  #db:
    #container_name: db
  #Use the official mysql image with tag mysql:5.7.
    #image: mysql:5.7
  #Configure environment variables to create an initial database and set user credentials
    #environment:
      #- MYSQL_DATABASE=wpdb
      # MYSQL_HOST: db
      #- MYSQL_ROOT_PASSWORD=wordpress
      # MYSQL_USER: root
  #The container must mount the db volume to the path /var/lib/mysql
    #volumes:
      #- db:/var/lib/mysql




