---
version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
  frontend:
    container_name: frontend
    build: ./frontend
    #Configure the environment variables
    environment:
      - BACKEND_DNS=backend
    depends_on:
      - backend
    ports:
      - "8080:8080"
