name: pipeline
on: push

jobs:
  Clone-down:
    name: Clone down repository
    runs-on: ubuntu-latest
    container: golang
    steps:
    - uses: actions/checkout@v2

    # run test
    - name: running test
    run: echo "Hello World!"
