name: pipeline
on: push

jobs:
  Clone_down:
    name: Clone down repository
    runs-on: ubuntu-latest
    container: golang

    # download repo
    steps:
    - name: Download repo
      uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
    
  Build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: Clone_down
    container: golang

    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: build stack
      run: docker-compose up -d

  Test:
    name: Test
    runs-on: ubuntu-latest
    container: golang

    steps: 
    - name: Runt test
      run: go test ./frontend ./...


        # build backend
#      - name: Build Backend
#        run: go build -v ./backend go build backend

        # build frontend
      - name: Build Frontend
        run: go build -v ./frontend go build frontend

        # run test
      - name: Run test
        run: go test ./frontend